# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy

class RaceItem(scrapy.Item):
    raceid = scrapy.Field()

    year = scrapy.Field()
    place = scrapy.Field()
    racenum = scrapy.Field()
    title = scrapy.Field()
    coursetype = scrapy.Field()
    distance = scrapy.Field()
    courseinfo1 = scrapy.Field()
    courseinfo2 = scrapy.Field()
    weather = scrapy.Field()
    condition = scrapy.Field()
    datetime = scrapy.Field()
    date = scrapy.Field()
    posttime = scrapy.Field()
    generation = scrapy.Field()
    racegrade = scrapy.Field()
    starters = scrapy.Field()
    addedmoneylist = scrapy.Field()
    requrl = scrapy.Field()

class PaybackItem(scrapy.Item):
    raceid = scrapy.Field()

    tansho = scrapy.Field()
    tanshopay = scrapy.Field()
    tanshofav = scrapy.Field()
    fukusho = scrapy.Field()
    fukushopay = scrapy.Field()
    fukushofav = scrapy.Field()
    wakuren = scrapy.Field()
    wakurenpay = scrapy.Field()
    wakurenfav = scrapy.Field()
    umaren = scrapy.Field()
    umarenpay = scrapy.Field()
    umarenfav = scrapy.Field()
    wide = scrapy.Field()
    widepay = scrapy.Field()
    widefav = scrapy.Field()
    umatan = scrapy.Field()
    umatanpay = scrapy.Field()
    umatanfav = scrapy.Field()
    fuku3 = scrapy.Field()
    fuku3pay = scrapy.Field()
    fuku3fav = scrapy.Field()
    tan3 = scrapy.Field()
    tan3pay = scrapy.Field()
    tan3fav = scrapy.Field()

class HorseResultItem(scrapy.Item):
    raceid = scrapy.Field()

    ranking = scrapy.Field()
    postnum = scrapy.Field()
    horsenum = scrapy.Field()
    horsename = scrapy.Field()
    sex = scrapy.Field()
    age = scrapy.Field()
    jockeyweight = scrapy.Field()
    jockey = scrapy.Field()
    time = scrapy.Field()
    margin  = scrapy.Field()
    fav = scrapy.Field()
    odds = scrapy.Field()
    last3f = scrapy.Field()
    passageratelist = scrapy.Field()
    affiliate = scrapy.Field()
    trainer = scrapy.Field()
    horseweight = scrapy.Field()
    horseweightdiff = scrapy.Field()
    horseurl = scrapy.Field()

class JrarecordItem(scrapy.Item):
    place = scrapy.Field()
    coursetype = scrapy.Field()
    generation = scrapy.Field()
    distance = scrapy.Field()
    courseinfo1 = scrapy.Field()
    courseinfo2 = scrapy.Field()
    time = scrapy.Field()
    horsename = scrapy.Field()
    sire = scrapy.Field()
    dam = scrapy.Field()
    sex = scrapy.Field()
    age = scrapy.Field()
    jockeyweight = scrapy.Field()
    jockey = scrapy.Field()
    jockeyfullname = scrapy.Field()
    date = scrapy.Field()
    weather = scrapy.Field()
    condition = scrapy.Field()
    reference = scrapy.Field()
